// Haunebu-Quests: Missionen und Varianten (Spec §5.2). Reine Daten.
// Karten-Zeichen: # Wand, . Boden, D Tür offen, L verschlossene Tür (Plus 70 Prozent), P Plattform (Start/Ziel),
// C Tresor, S Sabotageziel, X Missionsobjekt, K Stecker, ~ Deckung (Eis/Kisten: begehbar, blockiert Sicht).
// Variante: enemies [{ type, at:[x,y], dir (Grad, 0 = Osten, 90 = Süden), patrol:[[x,y,warteMs?,blickGrad?]…], look:[Grad…] }],
// patch [[x,y,Zeichen]…] verschiebt Beute/Ziele, coins {'x,y': n} überschreibt die Münzen je Tresor.
import { ARENA_BY_ID } from '../data.js';

export const MISSIONS = [
  {
    id: 'tachionenraub', name: 'Der Tachionenraub', place: 'Neuschwabenland, Tresor-Ebene', theme: 'neuschwabenland',
    lat: -72.0, lon: 5.0, timeMs: 360_000, coins: 2, reinforce: 'pinguin', gate: [19, 6],
    objective: { type: 'steal', min: 3, label: 'Tachionenbitcoins entführen' },
    intro: 'Unter dem Eis horten Hitlers Restposten die Tachionenbitcoins. Die Münzen sind schneller als das Licht, aber nicht schneller als Christian beim Kaufen. Klaut so viele wie möglich und bringt sie zur Haunebu.',
    hint: 'Klauen dauert 3 s pro Münze, jeder trägt höchstens 2. Ab 3 abgelieferten Münzen dürft ihr abheben.',
    texts: {
      success: 'Die Haunebu hebt ab, schwer beladen. Der Kurs steigt um 70 Prozent, bevor ihr überhaupt landet.',
      fail: 'Die Münzen bleiben im Eis. Christian kauft sie später teurer.',
    },
    map: [
      '################################',
      '#~~....#.C......C.#..C......C.~#',
      '#~.....L..........#............#',
      '#......#....~~....#....~~......#',
      '#......#..........#............#',
      '#......#########D######D####L###',
      '#~.....#................#......#',
      '#......#..~~........~~..#....C.#',
      '#......#...#........#...#......#',
      '#..PPP.#.......~~.......#..~~..#',
      '#..PPP.D.......~~.......D......#',
      '#..PPP.#.......~~.......#..~~..#',
      '#......#...#........#...#......#',
      '#......#..~~........~~..#....C.#',
      '#~.....#................#......#',
      '#......########D###########L####',
      '#......#...........#...........#',
      '#......#..~~.......#..C.....~~.#',
      '#......D...........D...........#',
      '#~.....#.......~~..#.....~~..C.#',
      '#~~....#...........#...........#',
      '################################',
    ],
    variants: [
      {
        id: 'schicht', name: 'Schichtwechsel', desc: 'Die Pinguine wechseln die Schicht. Himmler zählt im Südgang Schritte.',
        coins: { '29,13': 0, '22,17': 3 },
        enemies: [
          { type: 'pinguin', at: [9, 6], dir: 0, patrol: [[9, 6, 1000], [22, 6], [22, 14, 1000], [9, 14]] },
          { type: 'pinguin', at: [20, 3], dir: 0, patrol: [[20, 3, 1500, 0], [29, 3, 1500, 180]] },
          { type: 'pinguin', at: [12, 2], dir: 90, look: [90, 0, 180] },
          { type: 'drohne', at: [26, 7], dir: 90, patrol: [[26, 7, 800], [26, 13, 800]] },
          { type: 'himmler', at: [13, 18], dir: 0, look: [0, 180] },
          { type: 'pinguin', at: [21, 19], dir: 0, patrol: [[21, 19, 1200], [27, 17, 1200]] },
        ],
      },
      {
        id: 'inventur', name: 'Inventur', desc: 'Himmler macht mitten in der Halle Inventur, Goebbels übt im Südgang mit dem Megafon.',
        coins: { '9,1': 3, '16,1': 3, '21,1': 0, '22,17': 3, '29,19': 0 },
        enemies: [
          { type: 'himmler', at: [13, 10], dir: 0, look: [0, 90, 180, 270] },
          { type: 'goebbels', at: [9, 18], dir: 0, patrol: [[9, 18, 1500, 0], [18, 18, 1500, 180]] },
          { type: 'drohne', at: [9, 7], dir: 0, patrol: [[9, 7], [22, 7], [22, 13], [9, 13]] },
          { type: 'pinguin', at: [26, 8], dir: 0, patrol: [[26, 8, 2000, 0], [29, 10], [26, 12, 2000, 0]] },
          { type: 'pinguin', at: [24, 2], dir: 90, look: [90, 180, 0] },
          { type: 'pinguin', at: [25, 19], dir: 180, patrol: [[25, 19, 1000], [21, 16, 1000]] },
        ],
      },
      {
        id: 'drohnen', name: 'Drohnenschwarm', desc: 'Die Tachionen-Drohnen schieben Überstunden. Im Ost-Tresor liegt der Jackpot.',
        coins: { '9,1': 1, '16,1': 1, '21,1': 1, '28,1': 1, '29,7': 4, '29,13': 4, '22,17': 1, '29,19': 1 },
        enemies: [
          { type: 'drohne', at: [10, 6], dir: 0, patrol: [[10, 6, 500], [21, 6, 500]] },
          { type: 'drohne', at: [21, 14], dir: 180, patrol: [[21, 14, 500], [10, 14, 500]] },
          { type: 'drohne', at: [27, 10], dir: 180, patrol: [[27, 10, 1500, 180], [29, 10, 1500, 0]] },
          { type: 'pinguin', at: [10, 3], dir: 0, patrol: [[10, 3, 1000], [16, 3, 1000]] },
          { type: 'pinguin', at: [26, 3], dir: 180, look: [180, 90] },
          { type: 'pinguin', at: [9, 17], dir: 0, patrol: [[9, 17], [17, 17], [17, 19], [9, 19]] },
        ],
      },
    ],
  },
  {
    id: 'hangar', name: 'Hangar-Sabotage', place: 'Neuschwabenland, Hangar', theme: 'hangar',
    lat: -71.6, lon: 4.2, timeMs: 360_000, reinforce: 'pinguin', gate: [29, 20],
    objective: { type: 'sabotage', label: 'Ersatz-Flugscheiben sabotieren' },
    intro: 'Im Hangar stehen vier Ersatz-Flugscheiben. Ohne die kann Hitler dir die Haunebu nie wieder streitig machen. Micha sagt: Kondensator raus, Dosenbier in den Tank, fertig.',
    hint: 'Sabotage dauert 4 s je Flugscheibe. Danach alle, die noch stehen, auf die Plattform und abheben.',
    texts: {
      success: 'Vier Flugscheiben mit Dosenbier im Tank. Die heben nie wieder ab.',
      fail: 'Die Ersatz-Flugscheiben glänzen weiter. Hitler poliert schon.',
    },
    map: [
      '################################',
      '#.....#.........~~.........#...#',
      '#.PPP.#....................L...#',
      '#.PPP.#...S............S...#.~.#',
      '#.PPP.#....................#...#',
      '#.....#..~~...######...~~..##D##',
      '#~....#.......######.......#...#',
      '#~~...#.......######.......#...#',
      '#.....D..~~...######...~~..#...#',
      '#.....#....................#...#',
      '#.....#...S............S...#...#',
      '#.....#....................#...#',
      '#.....###########L#####D####...#',
      '#.....#....................#...#',
      '#.....#..##....~~....##....#...#',
      '#~....#..##..........##....#...#',
      '#~~...#....................D...#',
      '#.....D....~~......~~......#...#',
      '#.....#..##..........##....#...#',
      '#.....#..##....~~....##....#...#',
      '#.....#....................#...#',
      '################################',
    ],
    variants: [
      {
        id: 'nacht', name: 'Nachtschicht', desc: 'Zwei Pinguine in der Halle, eine Drohne in der Werkstatt, Goebbels bewacht den Werkstatt-Ausgang.',
        enemies: [
          { type: 'pinguin', at: [8, 1], dir: 0, patrol: [[8, 1, 1000], [25, 1, 1000]] },
          { type: 'pinguin', at: [12, 9], dir: 0, patrol: [[12, 9, 1500], [21, 9, 1500]] },
          { type: 'drohne', at: [10, 16], dir: 0, patrol: [[9, 16, 600], [25, 16, 600]] },
          { type: 'goebbels', at: [24, 14], dir: 180, look: [180, 90] },
          { type: 'pinguin', at: [29, 8], dir: 90, patrol: [[29, 8, 1500], [29, 18, 1500]] },
        ],
      },
      {
        id: 'leitstand', name: 'Leitstand-Prototyp', desc: 'Eine Flugscheibe steht im Leitstand. Himmler passt auf sie auf, mit Klemmbrett.',
        patch: [[23, 3, '.'], [29, 2, 'S']],
        enemies: [
          { type: 'himmler', at: [28, 1], dir: 90, look: [90, 0] },
          { type: 'pinguin', at: [10, 6], dir: 90, patrol: [[10, 6, 1000], [10, 11, 1000]] },
          { type: 'pinguin', at: [21, 1], dir: 90, patrol: [[21, 1, 800], [21, 11, 800]] },
          { type: 'drohne', at: [29, 7], dir: 90, patrol: [[29, 7, 1000], [29, 19, 1000]] },
          { type: 'pinguin', at: [8, 17], dir: 0, patrol: [[8, 17, 1000], [25, 17, 1000]] },
          { type: 'goebbels', at: [16, 10], dir: 90, look: [90, 0, 180] },
        ],
      },
      {
        id: 'werkstatt', name: 'Werkstatt-Chaos', desc: 'Eine Flugscheibe steht zur Reparatur mitten in der Werkstatt. Eine Drohne kreist drumherum.',
        patch: [[10, 10, '.'], [17, 16, 'S']],
        enemies: [
          { type: 'pinguin', at: [9, 2], dir: 0, patrol: [[9, 2, 1000], [24, 2, 1000]] },
          { type: 'pinguin', at: [25, 9], dir: 180, look: [180, 270] },
          { type: 'drohne', at: [12, 14], dir: 0, patrol: [[12, 14], [20, 14], [20, 19], [12, 19]] },
          { type: 'himmler', at: [17, 18], dir: 270, look: [270, 0, 180] },
          { type: 'pinguin', at: [29, 12], dir: 90, look: [90, 270] },
        ],
      },
    ],
  },
  {
    id: 'ps3', name: 'Michas PS3', place: 'PC Sale, Lager in Hagen', theme: 'pcsale',
    lat: ARENA_BY_ID.pcsale.lat, lon: ARENA_BY_ID.pcsale.lon, timeMs: 300_000, reinforce: 'detektiv', gate: [28, 17],
    fetchMs: 5000, pickupNoise: 7,
    objective: { type: 'fetch', label: 'Michas PS3 befreien' },
    intro: 'Der Ladendetektiv hat Michas PS3 im Lager eingeschlossen. Angeblich „Fundsache“. Holt sie raus und bringt sie zur Haunebu auf dem Parkplatz.',
    hint: 'Aufheben dauert 5 s, die Warensicherung piept dabei. Wer die PS3 trägt, ist 40 % langsamer und kann keine Kräfte einsetzen.',
    texts: {
      success: 'Die PS3 ist frei. Micha baut sie noch im Flug zur Hardware-Wallet um.',
      fail: 'Die PS3 bleibt im Regal. Neues Preisschild: plus 70 Prozent.',
    },
    map: [
      '##############################',
      '#~......................#....#',
      '#..####..####..####..~..#..X.#',
      '#.......................#.~..#',
      '#..####..####..####..~..#....#',
      '#~......................D..~.#',
      '#.........~~............#....#',
      '######D###################L###',
      '#.................#..........#',
      '#.#####...#####...#.##....~~.#',
      '#.................#..........#',
      '#.#####...#####...L....##....#',
      '#.................#..........#',
      '#...##.......~~...#.~~....##.#',
      '#.................#..........#',
      '#~...............~#..........#',
      '######D######D##########D#####',
      '#............................#',
      '#..PPP.....~~......~~........#',
      '#..PPP.....~~......~~........#',
      '#..PPP.......................#',
      '##############################',
    ],
    variants: [
      {
        id: 'ladenschluss', name: 'Ladenschluss', desc: 'Vier Detektive drehen ihre letzte Runde. Die PS3 liegt in der Gitterbox.',
        enemies: [
          { type: 'detektiv', at: [1, 10], dir: 0, patrol: [[1, 10, 1000], [17, 10, 1000]] },
          { type: 'detektiv', at: [1, 3], dir: 0, patrol: [[1, 3, 1500], [23, 3, 1500]] },
          { type: 'detektiv', at: [26, 12], dir: 180, look: [180, 270, 90] },
          { type: 'detektiv', at: [17, 14], dir: 180, patrol: [[17, 14, 1200], [1, 14, 1200]] },
        ],
      },
      {
        id: 'sommer', name: 'Sommerschlussverkauf', desc: 'Die PS3 liegt mitten im Lager. Himmler sitzt an der Kasse und zählt Wechselgeld.',
        patch: [[27, 2, '.'], [22, 6, 'X']],
        enemies: [
          { type: 'himmler', at: [4, 14], dir: 270, look: [270, 0] },
          { type: 'detektiv', at: [8, 8], dir: 0, patrol: [[1, 8, 800], [17, 8, 800], [17, 12, 800], [1, 12, 800]] },
          { type: 'detektiv', at: [12, 1], dir: 0, patrol: [[1, 1, 1000], [23, 1, 1000]] },
          { type: 'detektiv', at: [16, 5], dir: 180, patrol: [[23, 5, 1500], [8, 5, 1500]] },
          { type: 'detektiv', at: [24, 14], dir: 270, look: [270, 180] },
        ],
      },
      {
        id: 'chef', name: 'Chef im Büro', desc: 'Der Chef-Detektiv bewacht die Gitterbox persönlich. Im Büro wird Kaffee getrunken.',
        patch: [[27, 2, '.'], [25, 6, 'X']],
        enemies: [
          { type: 'detektiv', at: [27, 4], dir: 180, look: [180, 90, 270] },
          { type: 'detektiv', at: [20, 8], dir: 0, patrol: [[20, 8, 1500], [28, 8, 800], [28, 15, 1500], [20, 15, 800]] },
          { type: 'detektiv', at: [23, 12], dir: 180, look: [180, 0] },
          { type: 'detektiv', at: [2, 6], dir: 0, patrol: [[2, 6, 1000], [20, 6, 1000]] },
          { type: 'detektiv', at: [8, 12], dir: 0, patrol: [[8, 12, 800], [17, 12, 800]] },
        ],
      },
    ],
  },
  {
    id: 'keller', name: 'Kalter Keller', place: 'Keller der Rütherschanze', theme: 'keller',
    lat: ARENA_BY_ID.keller.lat, lon: ARENA_BY_ID.keller.lon, timeMs: 300_000, reinforce: 'pinguin', gate: [27, 2],
    objective: { type: 'unplug', label: 'Bitcoin-Heizung abschalten' },
    intro: 'Die Bitcoin-Heizung läuft heiß. Im Keller hat es 38 Grad, die Wachpinguine schwitzen. Zieht den Stecker und verschwindet unentdeckt, sonst zahlt Hildegard wieder die Stromrechnung.',
    hint: 'Den Stecker ziehen dauert 4 s. Danach alle zurück in den Garten auf die Plattform. Ohne Alarm gibt es einen Bonus.',
    texts: {
      success: 'Stecker raus, Ruhe im Keller. Die Pinguine bedanken sich mit einem Fisch.',
      fail: 'Die Heizung brummt weiter. 3000 Watt, auf Hildegards Rechnung.',
    },
    map: [
      '##############################',
      '#.PPP......~~........~~......#',
      '#.PPP........................#',
      '#.PPP......~~........~~......#',
      '######D#######################',
      '#............................#',
      '#...~~..............~~.......#',
      '#............................#',
      '####D########D#########L######',
      '#........#........#..........#',
      '#.~~..~~.#.##..##.#.~~.......#',
      '#........L........L..........#',
      '#.~~..~~.#.~~.....#...####..K#',
      '#........#........#...####...#',
      '#.~~..~~.#.##..##.#.~~.......#',
      '#........####D#####..........#',
      '#........#........#####D######',
      '#........#.#.#.#..#..........#',
      '#........D........D.~~.~~.~~.#',
      '#.~~..~~.#.#.#.#..#..........#',
      '#........#........#.~~.~~.~~.#',
      '##############################',
    ],
    variants: [
      {
        id: 'sauna', name: 'Sauna-Betrieb', desc: 'Die Pinguine schwitzen. Einer bewacht die Heizung, eine Drohne kühlt die Mining-Rigs.',
        enemies: [
          { type: 'pinguin', at: [14, 6], dir: 0, patrol: [[27, 6, 1000], [2, 6, 1000]] },
          { type: 'pinguin', at: [26, 14], dir: 270, look: [270, 180] },
          { type: 'drohne', at: [19, 17], dir: 0, patrol: [[19, 17, 1000], [28, 17, 1000]] },
          { type: 'pinguin', at: [11, 9], dir: 0, patrol: [[11, 9, 800], [17, 9, 800]] },
        ],
      },
      {
        id: 'wartung', name: 'Drohnen-Wartung', desc: 'Zwei Drohnen kreisen durch Flur und Heizungsraum. Ein Pinguin steht direkt am Stecker.',
        enemies: [
          { type: 'drohne', at: [20, 5], dir: 0, patrol: [[2, 5], [27, 5], [27, 7], [2, 7]] },
          { type: 'drohne', at: [24, 9], dir: 0, patrol: [[19, 9, 800], [28, 9, 800]] },
          { type: 'pinguin', at: [27, 13], dir: 180, look: [180, 270] },
          { type: 'pinguin', at: [10, 16], dir: 0, patrol: [[10, 16], [17, 16], [17, 20], [10, 20]] },
        ],
      },
      {
        id: 'hausbesuch', name: 'Hausbesuch', desc: 'Goebbels und Himmler wärmen sich an der Bitcoin-Heizung die Füße.',
        enemies: [
          { type: 'goebbels', at: [20, 13], dir: 0, look: [0, 90, 270] },
          { type: 'himmler', at: [26, 10], dir: 90, look: [90, 180] },
          { type: 'pinguin', at: [14, 7], dir: 0, patrol: [[28, 7, 1500], [1, 7, 1500]] },
          { type: 'pinguin', at: [2, 9], dir: 90, patrol: [[2, 9], [7, 9], [7, 20], [2, 20]] },
          { type: 'drohne', at: [11, 9], dir: 0, patrol: [[11, 9], [16, 9], [16, 13], [11, 13]] },
          { type: 'pinguin', at: [19, 19], dir: 0, patrol: [[19, 19, 1000], [28, 19, 1000]] },
        ],
      },
    ],
  },
];

export const MISSION_BY_ID = Object.fromEntries(MISSIONS.map(m => [m.id, m]));
export const pickVariant = (m, rng = Math.random) => m.variants[Math.floor(rng() * m.variants.length) % m.variants.length];
